version: '3.2'

## Overlay for running tests in Buildkite
services:
  feature:
    image: feature
    build:
      context: .
      dockerfile: ops/docker/Dockerfile
    environment:
      FEATURE_FLAGR_URL: 'http://flagr:18000'
    volumes:
      - .:/app:cached
    depends_on:
      - flagr

  flagr:
    image: ghcr.io/openflagr/flagr
    environment:
      FLAGR_DB_DBDRIVER: sqlite3
      FLAGR_DB_DBCONNECTIONSTR: "/tmp/flagr.db"
    ports:
      - 18000:18000

