name: eslint
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run eslint
        run: npx eslint . --ext .ts
